language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.2
    - android-23
    - platform-tools
    - extra-android-m2repository
    - extra-android-support

sudo: false

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
# must execute
# git update-index --chmod=+x gradlew
# instead of 
# - chmod +x gradlew
 
script:
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble test
